### PR TITLE
Panic on semantic error, instead of returning error

### LINKED ISSUE #29: Panic on semantic error, rather than returning error?
It seems `indextree` avoids panicking, even if there are semantic error (caused by broken inconsistent data).

For example:
https://github.com/saschagrunert/indextree/blob/0e512954beba93e1fcfcf004cc69b1419298b89c/src/lib.rs#L460-L471
In this code, if `self_borrow.last_child` was `None`, `self_borrow.first_child` should be also `None`, if `indextree` is working correctly.
If it is not, then the data can (and may) have been broken in unexpected way, and it seems meaningless to do more operation on that broken data.
Additionally, results are returned as `Fallible<_>` and it does type erasure, so users might easily miss such semantic bug.

I think semantic errors should be caught by panicking (typically `.expect()` on `Result` and `Option`) and assert macros.

### PR DESCRIPTION
**Pull request by lo48576**
Fixes #29 and #30.

* Now semantic errors (inconsistent data) results in panic (assertion failure) (#29).
    + Previously, they are returned as a usual error.
* `node.prepend(foo)` now successfully adds `foo` as the first children of `node` (#30).
    + Previously it is an error.

### CODE REVIEW

**Comment by lo48576** [comment]
This is non-breaking change (I think).

**Comment by saschagrunert** [comment]
Thanks for the PR, I'm honestly not sure if a `panic` is better than returning an error. Usually I would expect that the lib does not panic at all if we return an `Fallible<...>`.

**Comment by lo48576** [comment]
* If internal data is inconsistent, library user can do nothing about it, because internals are hidden from users and noone (including library developer) knows what happened.
  (If the library developer knows what happened, then it should be fixed before users use it).
* Additionally, users might have done something using the inconsistent (broken) data, then also any data outside the library might be wrong or inconsistent.
* Therefore, assertion failure indicates "the program has been already running in unexpected state", and such program is not expected to work correctly if it does not panic.

Library interface (including error type) represents specification.
Semantic error (bug) is not specification.
Therefore, internal consistency failure should not reported as return value.

File: src/lib.rs [hunk 1]
```diff
@@ -82,36 +82,47 @@ pub enum NodeError {
     #[fail(display = "Can not insert a node after itself")]
     InsertAfterSelf,
 
+    /// Deprecated, no longer used.
     #[fail(display = "First child is already set")]
     FirstChildAlreadySet,
```
Comment (saschagrunert) [inline src/lib.rs]: I think we should remove them. We cannot avoid a breaking change nevertheless. :)

Comment (lo48576) [reply src/lib.rs]: Ok. Removed the last commit, which adds that comments.

Comment (saschagrunert) [reply src/lib.rs]: No, I meant if the types are not used at all, we can completely remove them.

Comment (lo48576) [reply src/lib.rs]: Sorry, I misread them X-)

I didn't remove the unused variants because I think their existence are not so harmful, and we can wait until there are unavoidable breaking change (and indextree 4.0.0 is released).

Comment (lo48576) [reply src/lib.rs]: Some nervous users might test if such no-longer-used-variants is returned, but (in theory) such variants won't be emitted before and after this pull request.

```rust
match error.downcast<NodeError>().unwrap() {
    NodeError::FirstChildAlreadySet => {
        // User may try to do something here, but
        // this shouldn't have happened before and never happen in future.
    },
    ....
}
```

So it should be safe to leave them (and to remove later).

**Comment by lo48576** [comment]
Should I restore the "unused" comment?
